import React from 'react';
import { Download } from 'lucide-react';

const dummyInvoices = [
  {
    id: "242JWJODJ2OJ3JI4",
    // 1.EInvoice Detail
    irn: "01AMBPG7773M002AMBPG7773M002012345678901234567890123456789012345678901234567890",
    ackNo: "112010037461",
    ackDate: "16/07/2025 14:30:00",
    //2. Transaction Details
    suppltTypeCode:"B2B",
    documentNumber:"GT-45",
    IGSTapplicableDespiteSupplierAndRecipientLocatedInSameState : "yes",
    placeOfSupply: "GUJRAT",
    documentType: "Tax Invoice",
    documentDate: "04-07-2024",
    // 3. party details
    supplier : {
        GSTIN: "923256ewew5e66ew",
        address: "ijaio joidh ioawd oiahdoi hdihao hoiwah odh oahdn adjkah aioj RAJKOT 360003 GUJRAT",
        email : "kishanvyas@gmail.com"
    },
    recipient : {
        GSTIN: "923256ewew5e66ew",
        address: "ijaio joidh ioawd oiahdoi hdihao hoiwah odh oahdn adjkah aioj RAJKOT 360003 GUJRAT",
        email : "kishanvyas@gmail.com"
    },
    shipTo : {
        GSTIN: "923256ewew5e66ew",
        address: "ijaio joidh ioawd oiahdoi hdihao hoiwah odh oahdn adjkah aioj RAJKOT 360003 GUJRAT",
        email : "kishanvyas@gmail.com"
    },
    // 4.Details of Goods / Services
    items: [
      {
        slNo: 1,
        description: "COTTON YARN 30S COMBED",
        hsn: "5205",
        qty: 100,
        unit: "KGS",
        unitPrice: 250.00,
        discount: 0,
        taxableAmount: 25000.00,
        cgstRate: 9,
        cgstAmount: 2250.00,
        sgstRate: 9,
        sgstAmount: 2250.00,
        igstRate: 0,
        igstAmount: 0,
        totalAmount: 29500.00
      }
    ],
    totals: {
      TaxableAmount: 34000.00,
      CgstAmount: 3060.00,
      SgstAmount: 3060.00,
      IgstAmount: 0.00,
      CessAmount: 6120.00,
      Discount: 40120.00,
      OtherCharges: 0.00,
      RoundOffAmount: 92.00,
      TotalInvAmount: 40120.00,
    },
    // 5.Eway Bill Details
    EwayBillNo: "6232598295289",
    EwayBillDate: "16/07/2025 14:30:00",
    validTillDate: "16/07/2025 14:30:00",
    // 6.Generated By
    generatedBy: "jiiiwidwjdiwdwid",
    printDate: "16/07/2025 14:30:00"
  }
];

const EInvoiceReport = () => {
  const invoice = dummyInvoices[0];

  const generatePDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocked! Please allow pop-ups for this website to generate the PDF.');
      return;
    }
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Invoice - ${invoice.id}</title>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.3;
            color: #000;
            background: white;
          }
          .invoice-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            border: 2px solid #000;
            background: white;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 20px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 15px;
          }
          .company-info {
            flex: 1;
          }
          .company-name {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 5px;
          }
          .invoice-id {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
          }
          .qr-code {
            width: 120px;
            height: 120px;
            border: 1px solid #000;
            display: flex;
            align-items: center;
            justify-content: center;
            background: #f0f0f0;
            font-size: 10px;
            text-align: center;
          }
          .section {
            margin-bottom: 15px;
            border: 1px solid #000;
          }
          .section-header {
            background: #f0f0f0;
            padding: 5px 10px;
            font-weight: bold;
            border-bottom: 1px solid #000;
          }
          .section-content {
            padding: 10px;
          }
          .row {
            display: flex;
            margin-bottom: 5px;
          }
          .col-half {
            flex: 1;
            padding-right: 10px;
          }
          .col-half:last-child {
            padding-right: 0;
            padding-left: 10px;
          }
          .party-details {
            display: flex;
            gap: 10px;
          }
          .party-column {
            flex: 1;
            border-right: 1px solid #ccc;
            padding-right: 10px;
          }
          .party-column:last-child {
            border-right: none;
            padding-right: 0;
            padding-left: 10px;
          }
          .party-title {
            font-weight: bold;
            margin-bottom: 5px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
          }
          th, td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
            font-size: 10px;
          }
          th {
            background: #f0f0f0;
            font-weight: bold;
            text-align: center;
          }
          .text-right {
            text-align: right;
          }
          .text-center {
            text-align: center;
          }
          .totals-table {
            margin-top: 10px;
          }
          .totals-table td {
            padding: 3px 8px;
          }
          .eway-section {
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          .generated-by {
            margin-top: 20px;
            font-size: 10px;
          }
          .signature-section {
            margin-top: 30px;
            text-align: right;
          }
          @media print {
            body { margin: 0; }
            .invoice-container { border: none; margin: 0; padding: 15px; }
          }
        </style>
      </head>
      <body>
        <div class="invoice-container">
          <!-- Header -->
          <div class="header">
            <div class="company-info">
              <div class="invoice-id">${invoice.id}</div>
              <div class="company-name">WINTAS TEXTILES</div>
            </div>
            <div class="qr-code">
              QR CODE<br/>
              (Sample)
            </div>
          </div>

          <!-- 1. E-Invoice Details -->
          <div class="section">
            <div class="section-header">1. E-Invoice Details</div>
            <div class="section-content">
              <div class="row">
                <div class="col-half">
                  <strong>IRN:</strong> ${invoice.irn}
                </div>
                <div class="col-half">
                  <strong>Ack No.:</strong> ${invoice.ackNo} &nbsp;&nbsp;&nbsp; <strong>Ack Date:</strong> ${invoice.ackDate}
                </div>
              </div>
            </div>
          </div>

          <!-- 2. Transaction Details -->
          <div class="section">
            <div class="section-header">2. Transaction Details</div>
            <div class="section-content">
              <div class="row">
                <div class="col-half">
                  <strong>Supply type Code:</strong> ${invoice.suppltTypeCode}
                </div>
                <div class="col-half">
                  <strong>Document No.:</strong> ${invoice.documentNumber}
                </div>
              </div>
              <div class="row">
                <div class="col-half">
                  <strong>Place of Supply:</strong> ${invoice.placeOfSupply}
                </div>
                <div class="col-half">
                  <strong>IGST applicable despite Supplier and Recipient located in same State:</strong> ${invoice.IGSTapplicableDespiteSupplierAndRecipientLocatedInSameState}
                </div>
              </div>
              <div class="row">
                <div class="col-half">
                  <strong>Document Type:</strong> ${invoice.documentType}
                </div>
                <div class="col-half">
                  <strong>Document Date:</strong> ${invoice.documentDate}
                </div>
              </div>
            </div>
          </div>

          <!-- 3. Party Details -->
          <div class="section">
            <div class="section-header">3. Party Details</div>
            <div class="section-content">
              <div class="party-details">
                <div class="party-column">
                  <div class="party-title">Supplier:</div>
                  <div><strong>GSTIN:</strong> ${invoice.supplier.GSTIN}</div>
                  <div><strong>Address:</strong> ${invoice.supplier.address}</div>
                  <div><strong>Email:</strong> ${invoice.supplier.email}</div>
                </div>
                <div class="party-column">
                  <div class="party-title">Recipient:</div>
                  <div><strong>GSTIN:</strong> ${invoice.recipient.GSTIN}</div>
                  <div><strong>Address:</strong> ${invoice.recipient.address}</div>
                  <div><strong>Email:</strong> ${invoice.recipient.email}</div>
                </div>
              </div>
              <div style="margin-top: 15px;">
                <div class="party-title">Ship To:</div>
                <div><strong>GSTIN:</strong> ${invoice.shipTo.GSTIN}</div>
                <div><strong>Address:</strong> ${invoice.shipTo.address}</div>
                <div><strong>Email:</strong> ${invoice.shipTo.email}</div>
              </div>
            </div>
          </div>

          <!-- 4. Details of Goods / Services -->
          <div class="section">
            <div class="section-header">4. Details of Goods / Services</div>
            <div class="section-content">
              <table>
                <thead>
                  <tr>
                    <th>S.No</th>
                    <th>Item Description</th>
                    <th>HSN Code</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                    <th>Unit Price(Rs)</th>
                    <th>Discount(Rs)</th>
                    <th>Taxable Amount(Rs)</th>
                    <th>Tax Rate(GST + Cess)</th>
                    <th>Other Charges</th>
                    <th>Total</th>
                  </tr>
                </thead>
                <tbody>
                  ${invoice.items.map(item => `
                    <tr>
                      <td class="text-center">${item.slNo}</td>
                      <td>${item.description}</td>
                      <td class="text-center">${item.hsn}</td>
                      <td class="text-center">${item.qty}</td>
                      <td class="text-center">${item.unit}</td>
                      <td class="text-right">${item.unitPrice.toFixed(2)}</td>
                      <td class="text-right">${item.discount}</td>
                      <td class="text-right">${item.taxableAmount.toFixed(2)}</td>
                      <td class="text-center">
                        CGST ${item.cgstRate}%<br/>
                        SGST ${item.sgstRate}%<br/>
                        IGST ${item.igstRate}%<br/>
                        Cess ${item.cgstRate + item.sgstRate}%
                      </td>
                      <td class="text-right">0</td>
                      <td class="text-right">${item.totalAmount.toFixed(2)}</td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
              
              <table class="totals-table">
                <tr>
                  <td><strong>Taxable Amt</strong></td>
                  <td><strong>CGST Amt</strong></td>
                  <td><strong>SGST Amt</strong></td>
                  <td><strong>IGST Amt</strong></td>
                  <td><strong>CESS Amt</strong></td>
                  <td><strong>State CESS</strong></td>
                  <td><strong>Discount</strong></td>
                  <td><strong>Other Charges</strong></td>
                  <td><strong>Round off Amt</strong></td>
                  <td><strong>Tot Inv. Amt</strong></td>
                </tr>
                <tr>
                  <td class="text-right">${invoice.totals.TaxableAmount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.CgstAmount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.SgstAmount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.IgstAmount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.CessAmount.toFixed(2)}</td>
                  <td class="text-right">0.00</td>
                  <td class="text-right">${invoice.totals.Discount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.OtherCharges.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.RoundOffAmount.toFixed(2)}</td>
                  <td class="text-right">${invoice.totals.TotalInvAmount.toFixed(2)}</td>
                </tr>
              </table>
            </div>
          </div>

          <!-- 5. Eway Bill Details -->
          <div class="section">
            <div class="section-header">5. Eway Bill Details</div>
            <div class="section-content">
              <div class="eway-section">
                <div>
                  <strong>Eway Bill No.:</strong> ${invoice.EwayBillNo} &nbsp;&nbsp;&nbsp;
                  <strong>Eway Bill Date.:</strong> ${invoice.EwayBillDate} &nbsp;&nbsp;&nbsp;
                  <strong>Valid Till Date:</strong> ${invoice.validTillDate}
                </div>
                <div style="text-align: right;">
                  <div style="color: #0066cc; font-weight: bold; font-size: 14px;">eSign</div>
                  <div style="font-size: 9px;">Digitally Signed by NIC-IRP</div>
                  <div style="font-size: 9px;">on ${invoice.printDate}</div>
                </div>
              </div>
            </div>
          </div>

          <!-- Generated By -->
          <div class="generated-by">
            <strong>Generated By:</strong> ${invoice.generatedBy}<br/>
            <strong>Print Date:</strong> ${invoice.printDate}
          </div>
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load, then print
    printWindow.onload = function() {
      setTimeout(() => {
        printWindow.print();
      }, 500);
    };
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg p-6 mb-6">
        <h1 className="text-2xl font-bold text-gray-800 mb-4">Invoice PDF Generator - Dummy</h1>
        <p className="text-gray-600 mb-6">
          Generate and download PDF invoice based on the provided data structure.
        </p>
        
        <div className="bg-gray-50 p-4 rounded-lg mb-6">
          <h2 className="text-lg font-semibold mb-2">Invoice Details:</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="font-medium">Invoice ID:</span> {invoice.id}
            </div>
            <div>
              <span className="font-medium">Document No:</span> {invoice.documentNumber}
            </div>
            <div>
              <span className="font-medium">Date:</span> {invoice.documentDate}
            </div>
            <div>
              <span className="font-medium">Total Amount:</span> ₹{invoice.totals.TotalInvAmount.toFixed(2)}
            </div>
          </div>
        </div>

        <button
          onClick={generatePDF}
          className="flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors"
        >
          <Download size={20} />
          Download PDF Invoice
        </button>
      </div>

      
    </div>
  );
};

export default EInvoiceReport;