name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/kishanvyas/projects/Import-Export
          git pull origin main
          cd ./Frontend
          npm install
          cd ../Backend
          npm install

      - name: Restart PM2 apps
        run: |
          pm2 restart 1
          pm2 restart 5
          
      - name: Run NPM Audit (Security)
        run: |
          npm audit --production || true  # Prevents pipeline failure

      - name: Send Telegram Notification on Success
        if: success()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ *Deployment successful* on \`main\` branch.\n🖥️ Project: Import-Export\n🔁 PM2 restarted.\n👨‍💻 By: GitHub Actions" \
          -d parse_mode=Markdown

      - name: Send Telegram Notification on Failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ *Deployment failed* on \`main\` branch!\nPlease check GitHub Actions logs." \
          -d parse_mode=Markdown
