name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/kishanvyas/projects/Import-Export
          git pull origin main
          npm install

      - name: Restart PM2 apps
        run: |
          pm2 restart 1
          pm2 restart 5
